package core;

import useless.SwingGUI;
import java.awt.EventQueue;

public class App {
    
    //================================================================================
    // Fields
    //================================================================================

    private SwingGUI appFrame;
    private ResourcesManager rManager;

    //================================================================================
    // Constructors
    //================================================================================
    App() {
        initResourcesManager(rManager);
        initAppFrame(appFrame);
    }
    
    //================================================================================
    // Methods
    //================================================================================
    private void initAppFrame(SwingGUI frame) {
        frame = new SwingGUI(rManager);
        frame.setVisible(true);    
    }
    
    private void initResourcesManager(ResourcesManager rm) {
        rm = new ResourcesManager();
    }
    
    public static void main(String[] args) {
        //Autogenerated code
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SwingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SwingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SwingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SwingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App();
            }
        });
    }
    
    //================================================================================
    // Accessors
    //================================================================================

    public ResourcesManager getrManager() {
        return rManager;
    }
    
    
}
